app:
  dashboard_url: "${PANGOLIN_DASHBOARD_URL}"
  log_level: debug

domains:
  domain1:
    base_domain: "${BASE_DOMAIN}"

server:
  baseUrl: "${PANGOLIN_DASHBOARD_URL}"
  secret: "${PANGOLIN_SERVER_SECRET}"

gerbil:
  base_endpoint: "${PANGOLIN_DASHBOARD_URL}"

headscale:
  url: "${HEADSCALE_SERVER_URL}"
  
orgs:
  block_size: 24
  subnet_group: 100.90.137.0/20

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: true
  allow_raw_resources: true
  enable_integration_api: true
  enable_clients: true

auth:
  method: none

logging:
  level: debug

db:
  type: sqlite
  path: /app/data/db.sqlite
