---
log_level: info
# The url clients will connect to.
server_url: https://headscale.t99ltd.com

# Address to listen to / bind to on the server
listen_addr: 0.0.0.0:8080

# Address to listen to /metrics, you may want
metrics_listen_addr: 127.0.0.1:9090

# Address to listen for gRPC.
grpc_listen_addr: 127.0.0.1:50443

# Allow the gRPC admin interface to run in INSECURE mode.
grpc_allow_insecure: false

noise:
  # The Noise private key is used to encrypt the traffic
  private_key_path: /var/lib/headscale/noise_private.key

# List of IP prefixes to allocate tailaddresses from.
# Each prefix consists of either an IPv4 or IPv6 address,
prefixes:
  v6: fd7a:115c:a1e0::/48
  v4: 100.64.0.0/10
  # Strategy used for allocation of IPs to nodes, available options:
  # - sequential (default): assigns the next free IP from the previous given IP.
  # - random: assigns the next free IP from a pseudo-random IP generator (crypto/rand).
  allocation: sequential

# DERP is a relay system that Tailscale uses when a direct connection cannot be established.
derp:
  server:
    enabled: false
    # Region ID to use for the embedded DERP server.
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    # Listens over UDP at the configured address for STUN connections - to help with NAT traversal.
    stun_listen_addr: "0.0.0.0:3478"
    # Private key used to encrypt the traffic between headscale DERP and Tailscale clients.
    private_key_path: /var/lib/headscale/derp_server_private.key
    # This flag can be used, so the DERP map entry for the embedded DERP server is not written automatically,
    automatically_add_embedded_derp_region: true
    # For better connection stability (especially when using an Exit-Node and DNS is not working),
    ipv4: 1.2.3.4
    ipv6: 2001:db8::1
  # List of externally available DERP maps encoded in JSON
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  # Locally available DERP map files encoded in YAML
  paths: []
  # If enabled, a worker will be set up to periodically refresh the given sources and update the derpmap
  auto_update_enabled: true
  # How often should we check for DERP updates?
  update_frequency: 24h
# Disables the automatic check for headscale updates on startup
disable_check_updates: false
# Time before an inactive ephemeral node is deleted?
ephemeral_node_inactivity_timeout: 30m
database:
  type: sqlite
  # Enable debug mode. This setting requires the log.level to be set to "debug" or "trace".
  debug: false
  gorm:
    prepare_stmt: true
    parameterized_queries: true
    skip_err_record_not_found: true
    slow_threshold: 1000
  sqlite:
    path: /var/lib/headscale/db.sqlite
    write_ahead_log: true
  
  ### TLS configuration Let's encrypt / ACME
acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: "your-email-goes-here@tutorial.example"
tls_letsencrypt_hostname: ""
# Path to store certificates and metadata needed by letsencrypt
tls_letsencrypt_cache_dir: /var/lib/headscale/cache

# Type of ACME challenge to use, currently supported types: HTTP-01 or TLS-ALPN-01
tls_letsencrypt_challenge_type: HTTP-01
# When HTTP-01 challenge is chosen, letsencrypt must set up a verification endpoint, and it will be listening on:
tls_letsencrypt_listen: ":http" # :http = port 80
tls_cert_path: ""
tls_key_path: ""

log:
  format: text # text or json
  level: info

policy:
  mode: file
  path: ""

dns:
  magic_dns: true
  # Defines the base domain to create the hostnames for MagicDNS.
  base_domain: head.local
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001
    split: {}
  search_domains: []
  # Extra DNS records
  extra_records: []
  
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"
logtail:
  # Enable logtail for this headscales clients.
  enabled: false
# Enabling this option makes devices prefer a random port for WireGuard traffic over the default static port 41641.
randomize_client_port: false
